<template>
  <LoadingPage v-if="isLoading" @complete="isLoading = false"></LoadingPage>
  <div :hidden="isLoading" class="page" ref="scrollContainer">
    <!-- 左侧悬浮菜单栏 -->
    <LeftMenu />
    <MusicControl />
    <div
      class="top-scroll-container"
      :style="{ height: `${totalScrollHeight}px` }"
    >
      <HomeBg :blurPx="params.blurPx" />
      <!--  首页第一屏    -->
      <div class="part-wrapper home-bg">
        <div
          class="main-logo"
          :style="{
            height: `${clientHeight * params.logoHeightPer}px`,
            width: `${clientHeight * params.logoHeightPer * (816 / 593)}px`,
            left: `${params.logoLeftPos}%`,
            top: `${params.logoTopPos}%`,
          }"
        >
          <img src="../public/images/main_logo.png" class="main-img" />
          <img
            class="main-logo-banner"
            src="../public/images/main_logo_text.png"
            :style="{ opacity: params.logoBannerOpacity }"
          />
        </div>
        <div
          class="main-btn"
          :style="{
            transform: `translateX(50%) scale(${params.mainBtnScale})`,
            bottom: `${params.mainBtnBottomPos}%`,
            right: `${params.mainBtnRightPos}%`,
          }"
          @click="onClickPlayBtn"
        ></div>
      </div>
      <MainDesk :deskPos="params.deskPos" />
      <div
        class="part-wrapper shelf-bg"
        :style="{
          transform: `scale(${params.shelfScale}) translateY(${params.shelfPos}px)`,
          filter: `blur(${params.shelfBlurPx}px)`,
          zIndex: params.shelfBlurPx === 0 ? 100 : 0,
        }"
      >
        <div
          class="shelf-title"
          :style="{ top: 'calc(10% + 0.9%)', color: '#AF4FDC' }"
        >
          Features
        </div>
        <div class="shelf-title">Features</div>
        <div class="light-wrapper">
          <div class="single-lamp">
            <div class="halo"></div>
            <div
              class="text-area"
              @click="
                lampTextPopup =
                  'CheersLand powers all classic games with Blockchain and GameFi and rewards users for their engagement. Users can play and build games to become the beneficiaries and the owners of the ecosystem.'
              "
            >
              Multi-game Universe
            </div>
          </div>
          <div class="single-lamp">
            <div class="halo"></div>
            <div
              class="text-area"
              @click="
                lampTextPopup =
                  'The gamified launchpad for startups is named Initial Gaming Offering (IGO) in CheersLand, which can also provide them with advertising and promotion services in the game beside raising capitals.'
              "
            >
              Gamified Launchpad
            </div>
          </div>
          <div class="single-lamp">
            <div class="halo"></div>
            <div
              class="text-area"
              @click="
                lampTextPopup =
                  'CHEERS holders will be able to decide the future of the CheersLand ecosystem. All the revenue generated by CheersLand will be placed in the Community Vault governed by the CHEERS holders once the network has become sufficiently decentralized.'
              "
            >
              Optimistic Governance
            </div>
          </div>
        </div>
        <teleport to="body">
          <transition name="fade">
            <FeaturePopup
              :overrideText="lampTextPopup"
              v-if="lampTextPopup"
              @close="lampTextPopup = ''"
            ></FeaturePopup>
          </transition>
        </teleport>
      </div>
      <div
        class="part-wrapper chair-bg"
        ref="chairBg"
        :style="{
          opacity: params.chairOpacity,
          transform: `scale(${params.chairScale}) translateY(${params.chairPos}px)`,
        }"
      >
        <img
          src="../public/images/sponsor_logo_1.png"
          class="sponsor-logo"
          style="top: 28%; left: 4.8%"
        />
        <img
          src="../public/images/sponsor_logo_2.png"
          class="sponsor-logo"
          style="top: 28%; left: 44.2%"
        />
        <img
          src="../public/images/sponsor_logo_3.png"
          class="sponsor-logo"
          style="top: 28%; left: 81.8%"
        />
      </div>
    </div>
    <div class="part-wrapper purple-bg">
      <img class="fog-bg" src="../public/images/fog_01.png" />
      <img class="fog-bg fog-bg-second" src="../public/images/fog_01.png" />
      <div class="scroll-panel">
        <div class="scroll-item">
          <div class="scroll-title">Play to Earn</div>
          <div class="scroll-text">
            Gamers can get the rankings on Ranking List by playing games and get
            diversified rewards for their engagement.
          </div>
        </div>
        <div class="scroll-item">
          <div class="scroll-title">NFT Market</div>
          <div class="scroll-text">
            Users can mint NFTs of in-game items and trade them in NFT Market,
            including Pass Card, VIP Seat, LP Miner, etc..
          </div>
        </div>
        <div class="scroll-item">
          <div class="scroll-title">Build to Earn</div>
          <div class="scroll-text">
            Game builders are allowed to use CheersLand API to launch the games
            and share the economy to earn rewards.
          </div>
        </div>
        <div class="scroll-item">
          <div class="scroll-title">Weekly Tournaments</div>
          <div class="scroll-text">
            Weekly Tournaments, titled by the sponsors, will take a weekly
            snapshot of Ranking List and reward the gamers on it.
          </div>
        </div>
        <div class="scroll-item">
          <div class="scroll-title">Multi-asset Staking</div>
          <div class="scroll-text">
            Gamers can stake designated tokens to earn HP and get more chances
            to win the games while receiving rewards.
          </div>
        </div>
        <div class="scroll-item">
          <div class="scroll-title">Invitation Mechanism</div>
          <div class="scroll-text">
            Gamers can use the exclusive link to invite friends through social
            networks in CheersLand to earn HPs together.
          </div>
        </div>
      </div>
    </div>
    <div class="part-wrapper revert-purple-bg">
      <div class="up-down-revert"></div>
      <div
        class="bg-cover"
        @click="
          treasureMapTitle = '';
          treasureMapText = [];
          treasureMapAppendix = '';
        "
      >
        <div class="treasure-map">
          <div
            class="phase-text"
            @click.stop="
              treasureMapTitle = 'Q2 2021';
              treasureMapText = [
                'Market research of GameFi √',
                'Design for multiple games framework √',
                'BSC-based Staking Contract test √',
                'BSC-based Invitation Contract test √',
              ];
            "
          >
            Q2 2021
          </div>
          <div
            class="phase-text"
            @click.stop="
              treasureMapTitle = 'Q3 2021';
              treasureMapText = [
                'Audit to the Staking and Invitation Contract √',
                'Launch of the first Classic Game √',
                'Launch of whitepaper V1.0 and tokenomics √',
                'Community building and growth',
                'IGO MVP pre-release on BSC',
                'Public Sale of CHEERS',
              ];
            "
          >
            Q3 2021
          </div>
          <div
            class="phase-text"
            @click.stop="
              treasureMapTitle = 'Q4 2021';
              treasureMapText = [
                'Official launch and operation of IGO',
                'Establishment of the Community Vault',
                'Launch of the second Classic Game',
                'Deployment on the multichain ecosystem e.g. Solona, Polygon, Polkadot',
                'Launch of Multi-asset Staking Platform',
                'Launch of NFT Market Beta',
              ];
            "
          >
            Q4 2021
          </div>
          <div
            class="phase-text"
            @click.stop="
              treasureMapTitle = 'Q1 2022';
              treasureMapText = [
                'Announcement of the annual revenue and buyback & burn plan',
                'Launch of the third Classic Game',
                'Improvement of Community Governance model',
                'CheersLand API for Build to Earn',
              ];
            "
          >
            Q1 2022
          </div>
          <div
            class="phase-text"
            @click.stop="
              treasureMapTitle = 'Q2 2022';
              treasureMapText = [
                'New GameFi programme integrations',
                'Eco Marathon Grant Activities',
                'The fourth Classic Game launched by the community',
                'Second audit to all contracts',
                'On-board new blockchain ecosystems',
              ];
            "
          >
            Q2 2022
          </div>
          <div
            class="phase-text"
            @click.stop="
              treasureMapTitle = 'Q3 2022';
              treasureMapText = [
                'More partnerships with the GameFi ecosystem',
                'The fifth Classic Game released by the community',
              ];
              treasureMapAppendix = 'To Be Announced';
            "
          >
            Q3 2022
          </div>
          <div class="detail-layer" v-if="!!treasureMapTitle" @click.stop="">
            <div class="title">{{ treasureMapTitle }}</div>
            <div class="text">
              <ul>
                <li v-for="text in treasureMapText" :key="text">
                  {{ text }}
                </li>
                <div v-if="treasureMapAppendix" style="margin-top: 0.12rem">
                  {{ treasureMapAppendix }}
                </div>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </div>
    <Footer />
  </div>
</template>

<script lang="ts">
import { defineComponent } from "vue";
import LeftMenu from "./components/LeftMenu.vue";
import MusicControl from "@/components/MusicControl.vue";
import HomeBg from "@/components/HomeBg.vue";
import MainDesk from "@/components/MainDesk.vue";
import Footer from "@/components/Footer.vue";
import FeaturePopup from "@/components/FeaturePopup.vue";
import LoadingPage from "@/components/LoadingPage.vue";

let lastScrollTop: number;

const clientHeight = document.documentElement.clientHeight;
const deskStayHeight = 230;
const shelfStayHeight = 230;
const chairStayHeight = 230;
const mainBtnBottomPercent =
  100 - ((62 + 117 * 0.24) / clientHeight + 0.08) * 100;

const deskStartFadeOutHeight = clientHeight + deskStayHeight;
const shelfEndFadeInHeight = deskStartFadeOutHeight + clientHeight;
const shelfStartFadeOutHeight = shelfEndFadeInHeight + shelfStayHeight;
const chairEndFadeInHeight = shelfStartFadeOutHeight + clientHeight;
const chairStartMoveUpHeight = chairEndFadeInHeight + chairStayHeight;
const defaultParams = {
  blurPx: 0,
  deskPos: clientHeight,
  shelfPos: clientHeight,
  shelfScale: 1,
  shelfBlurPx: 0,
  chairOpacity: 0,
  chairScale: 1.2,
  chairPos: 200,
  logoLeftPos: 50,
  logoTopPos: 40,
  logoHeightPer: 0.5,
  logoBannerOpacity: 1,
  mainBtnRightPos: 50,
  mainBtnBottomPos: 10,
  mainBtnScale: 1,
};

export default defineComponent({
  name: "App",
  data() {
    return {
      isLoading: true,
      clientHeight,
      params: defaultParams,
      totalScrollHeight:
        clientHeight * 4 + deskStayHeight + shelfStayHeight + chairStayHeight,
      lampTextPopup: "",
      treasureMapTitle: "",
      treasureMapText: [],
      treasureMapAppendix: "",
    };
  },
  components: {
    LeftMenu,
    MusicControl,
    HomeBg,
    MainDesk,
    Footer,
    FeaturePopup,
    LoadingPage,
  },
  mounted(): void {
    document.documentElement.style.fontSize = `${
      (100 * clientHeight) / 1080
    }px`;
    window.addEventListener("scroll", this.onPageScroll, true);
  },
  beforeUnmount() {
    window.removeEventListener("scroll", this.onPageScroll, true);
  },
  methods: {
    onClickPlayBtn() {
      window.open("/game.html", "_blank");
    },
    onPageScroll() {
      const { scrollTop } = document.documentElement;
      if (scrollTop === lastScrollTop) return;
      lastScrollTop = scrollTop;
      this.params.blurPx = 0;
      this.params.deskPos = clientHeight;
      this.params.shelfPos = clientHeight;
      this.params.shelfScale = 1;
      this.params.shelfBlurPx = 0;
      this.params.chairOpacity = 0;
      this.params.chairScale = 1.2;
      this.params.chairPos = 200;
      this.params.logoLeftPos = 10.6;
      this.params.logoTopPos = 14.3;
      this.params.logoHeightPer = 0.17;
      this.params.logoBannerOpacity = 0;
      this.params.mainBtnScale = 0.53;
      this.params.mainBtnBottomPos = mainBtnBottomPercent;
      this.params.mainBtnRightPos = 18;

      if (scrollTop < clientHeight) {
        const partPercent = scrollTop / clientHeight;
        this.params.blurPx = partPercent * 10;
        this.params.deskPos = clientHeight - scrollTop;
        this.params.logoLeftPos = -39.4 * partPercent + 50;
        this.params.logoTopPos = -25.7 * partPercent + 40;
        this.params.logoHeightPer = -0.33 * partPercent + 0.5;
        this.params.logoBannerOpacity = 1 - partPercent;
        this.params.mainBtnRightPos = 50 - partPercent * 32;
        this.params.mainBtnBottomPos =
          10 + partPercent * (mainBtnBottomPercent - 10);
        this.params.mainBtnScale = Math.max(1 - partPercent * 5, 0.53);
        return;
      }
      if (scrollTop <= deskStartFadeOutHeight) {
        this.params.blurPx = 10;
        this.params.deskPos = 0;
        return;
      }
      if (scrollTop <= shelfEndFadeInHeight) {
        this.params.blurPx = 10;
        this.params.deskPos = deskStartFadeOutHeight - scrollTop;
        this.params.shelfPos = shelfEndFadeInHeight - scrollTop;
        return;
      }
      if (scrollTop <= shelfStartFadeOutHeight) {
        this.params.blurPx = 10;
        this.params.deskPos = -1 * clientHeight;
        this.params.shelfPos = 0;
        return;
      }
      if (scrollTop <= chairEndFadeInHeight) {
        const partPercent =
          (scrollTop - shelfStartFadeOutHeight) / clientHeight;
        this.params.blurPx = 10;
        this.params.deskPos = -1 * clientHeight;
        this.params.shelfPos = 0;
        this.params.shelfBlurPx = partPercent * 10;
        if (partPercent < 0.4) {
          this.params.shelfScale = 1 - partPercent;
        } else if (partPercent <= 0.6) {
          this.params.shelfScale = 0.6;
          this.params.chairOpacity = 5 * (partPercent - 0.4);
          this.params.chairScale = 1.2 - (partPercent - 0.4);
          this.params.chairPos = 200 - (partPercent - 0.4) * 1000;
        } else {
          this.params.shelfScale = 0.6;
          this.params.chairOpacity = 1;
          this.params.chairScale = 1;
          this.params.chairPos = 0;
        }
        return;
      }
      if (scrollTop <= chairStartMoveUpHeight) {
        this.params.blurPx = 10;
        this.params.deskPos = -1 * clientHeight;
        this.params.shelfPos = 0;
        this.params.shelfBlurPx = 10;
        this.params.shelfScale = 0.6;
        this.params.chairOpacity = 1;
        this.params.chairScale = 1;
        this.params.chairPos = 0;
        // eslint-disable-next-line @typescript-eslint/ban-ts-comment
        // @ts-ignore
        this.$refs.chairBg.style.transition = "none";
        return;
      }
      if (scrollTop <= this.totalScrollHeight) {
        this.params.blurPx = 10;
        this.params.deskPos = -1 * clientHeight;
        this.params.shelfBlurPx = 10;
        this.params.shelfScale = 0.6;
        this.params.chairOpacity = 1;
        this.params.chairScale = 1;
        this.params.chairPos = -1 * (scrollTop - chairStartMoveUpHeight);
        this.params.shelfPos = -1 * (scrollTop - chairStartMoveUpHeight);
        return;
      }
      this.params.blurPx = 10;
      this.params.deskPos = -1 * clientHeight;
      this.params.shelfBlurPx = 10;
      this.params.shelfScale = 0.6;
      this.params.chairOpacity = 1;
      this.params.chairScale = 1;
      this.params.chairPos = -1 * clientHeight;
      this.params.shelfPos = -1 * clientHeight;
    },
  },
});
</script>

<style lang="less">
@font-face {
  font-family: Righteous;
  src: url("../public/fonts/Righteous-Regular.ttf");
}

@font-face {
  font-family: Risque;
  src: url("../public/fonts/Risque-Regular.ttf");
}

@font-face {
  font-family: Racing-Sans-One;
  src: url("../public/fonts/RacingSansOne-Regular.ttf");
}

@font-face {
  font-family: Rakkas;
  src: url("../public/fonts/Rakkas-Regular.ttf");
}

html {
  scroll-behavior: smooth;
}

div {
  box-sizing: border-box;
}

body {
  margin: 0;
  font-size: 0;
  -webkit-overflow-scrolling: touch;
}

@keyframes shake {
  from {
    transform: rotate(-5deg);
  }

  50% {
    transform: rotate(5deg);
  }

  to {
    transform: rotate(-5deg);
  }
}

@keyframes shake-minor {
  from {
    transform: rotate(-3deg);
  }

  50% {
    transform: rotate(3deg);
  }

  to {
    transform: rotate(-3deg);
  }
}

@keyframes bump {
  from {
    transform: scale(1);
  }

  50% {
    transform: scale(1.2);
  }

  to {
    transform: scale(1);
  }
}

@keyframes shining {
  from {
    opacity: 0.6;
    transform: scale(0.8);
  }

  50% {
    opacity: 1;
    transform: scale(1.5);
  }

  to {
    opacity: 0.6;
    transform: scale(0.8);
  }
}

@keyframes shinning-minor {
  from {
    opacity: 0.7;
    transform: scale(0.9);
    filter: blur(5px);
  }

  50% {
    opacity: 1;
    transform: scale(1.1);
    filter: blur(10px);
  }

  to {
    opacity: 0.7;
    transform: scale(0.9);
    filter: blur(5px);
  }
}

.top-scroll-container {
}

.part-wrapper {
  position: relative;
  width: 100vw;
  height: 100vh;
  background-size: 100vw 100vh;
}

.home-bg {
  .main-logo {
    position: fixed;
    left: 50%;
    top: 40%;
    transform: translate(-50%, -50%);
    transition: all 0.3s ease-out;
    z-index: 1000;

    .main-img {
      height: 100%;
      width: 100%;
    }

    .main-logo-banner {
      position: absolute;
      top: 75%;
      transform: translateX(-50%);
      left: 50%;
      height: calc(100% * 139 / 593);
      width: auto;
    }
  }

  .main-btn {
    position: fixed;
    bottom: 10%;
    right: 50%;
    width: 453px;
    height: 117px;
    transform: translateX(50%);
    background-image: url("../public/images/play_btn.png");
    background-size: cover;
    z-index: 1000;
    cursor: pointer;
  }
}

.shelf-bg {
  position: fixed;
  left: 0;
  right: 0;
  top: 0;
  bottom: 0;
  background-image: url("../public/images/shelf_bg.png");
  background-size: 100vw 100vh;
  transform-origin: top center;

  .shelf-title {
    position: absolute;
    left: 50%;
    top: 10%;
    transform: translateX(-50%);
    width: 50%;
    text-align: center;
    font-family: Risque;
    font-style: normal;
    font-weight: normal;
    font-size: 1.44rem;
    line-height: 1.1;
    color: #4fc3dc;

    &-shadow {
      position: absolute;
      top: 2px;
      left: 2px;
    }
  }

  .light-wrapper {
    position: absolute;
    bottom: 24%;
    left: 16%;
    width: 68%;
    height: 364px;
    display: flex;
    align-items: flex-end;
    justify-content: space-between;

    .single-lamp {
      position: relative;
      width: calc(100vw * (404 / 1920));
      height: calc(100vh * (364 / 1080));
      background-image: url("../public/images/single_lamp.png");
      background-size: calc(100vw * (404 / 1920)) calc(100vh * (364 / 1080));
      background-repeat: no-repeat;
      font-family: Righteous;
      font-style: normal;
      font-weight: normal;
      font-size: 0.36rem;
      line-height: 1.25;
      text-align: center;
      color: #214f79;

      @keyframes center-shinning-minor {
        from {
          opacity: 0.5;
          transform: translate(-50%, -50%) scale(0.9);
          filter: blur(5px);
        }

        50% {
          opacity: 1;
          transform: translate(-50%, -50%) scale(1.3);
          filter: blur(10px);
        }

        to {
          opacity: 0.5;
          transform: translate(-50%, -50%) scale(0.9);
          filter: blur(5px);
        }
      }

      .halo {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translate(-50%, -50%);
        background-image: url("../public/images/single_lamp_halo.png");
        background-size: calc(100vw * (423 / 1920)) calc(100vh * (428 / 1080));
        width: calc(100vw * (423 / 1920));
        height: calc(100vh * (428 / 1080));
        animation-name: center-shinning-minor;
        animation-duration: 2.5s;
        animation-iteration-count: infinite;
      }

      .text-area {
        position: absolute;
        top: 5%;
        left: 25%;
        width: 50%;
        height: 60%;
        align-items: center;
        display: flex;
        justify-content: center;
        cursor: pointer;
      }
    }
  }
}

.chair-bg {
  position: fixed;
  left: 0;
  right: 0;
  bottom: 0;
  background-image: url("../public/images/chairs_bg.png");
  transform-origin: bottom center;
  transition: 0.4s ease-out all;

  .sponsor-logo {
    position: absolute;
    width: calc(100vw * (279 / 1920));
    height: calc(100vh * (279 / 1080));
  }
}

@keyframes circle {
  from {
    transform: translateX(0);
  }

  to {
    transform: translateX(100%);
  }
}

@keyframes circle-two {
  from {
    transform: translateX(-100%);
  }

  to {
    transform: translateX(0);
  }
}

.fog-bg {
  position: absolute;
  width: auto;
  height: 100vh;
  animation-name: circle;
  animation-iteration-count: infinite;
  animation-timing-function: linear;
  animation-duration: 30s;
}

.fog-bg-second {
  animation-name: circle-two;
}

.purple-bg {
  background-image: url("../public/images/purple_bg.png");

  .scroll-panel {
    position: absolute;
    top: 15%;
    left: 15%;
    width: 70%;
    display: flex;
    flex-wrap: wrap;
    justify-content: space-between;

    .scroll-item {
      width: calc(20vw);
      height: calc(40vh);
      background-image: url("../public/images/scroll_bg.png");
      background-size: 20vw 40vh;
      background-repeat: no-repeat;
      padding: 5% 5%;

      .scroll-title {
        font-family: Racing-Sans-One;
        font-style: normal;
        font-weight: normal;
        font-size: 0.24rem;
        line-height: 1.2;
        color: #b57008;
        margin-bottom: 0.16rem;
        text-align: center;
      }

      .scroll-text {
        font-family: Righteous;
        font-style: normal;
        font-weight: normal;
        font-size: 0.2rem;
        line-height: 1.25;
        color: #b57008;
      }
    }
  }
}

.revert-purple-bg {
  .up-down-revert {
    position: absolute;
    left: 0;
    top: 0;
    width: 100vw;
    height: 100vh;
    background-size: 100vw 100vh;
    background-image: url("../public/images/purple_bg.png");
    transform: rotate(180deg);
  }

  .bg-cover {
    position: absolute;
    top: 0;
    left: 0;
    right: 0;
    bottom: 0;
    display: flex;
    align-items: center;
    justify-content: center;
    z-index: 100;

    .treasure-map {
      width: calc(100vw * (1494 / 1920));
      height: calc(100vh * (841 / 1080));
      background-image: url("../public/images/treasure_map.png");
      background-size: cover;
      position: relative;

      @keyframes pulse {
        from,
        to {
          transform: scale3d(1, 1, 1);
        }

        50% {
          transform: scale3d(1.05, 1.05, 1.05);
        }
      }

      .phase-text {
        position: absolute;
        font-family: Rakkas;
        font-size: 0.48rem;
        line-height: 1.75;
        color: #6a1a1a;
        animation-name: pulse;
        animation-iteration-count: infinite;
        animation-duration: 1s;
        animation-timing-function: ease-in-out;
        cursor: pointer;

        &:nth-child(1) {
          top: 14%;
          left: 7.5%;
          animation-delay: 0.2s;
        }
        &:nth-child(2) {
          top: 35%;
          left: 23.5%;
          animation-delay: 0.4s;
        }
        &:nth-child(3) {
          top: 38%;
          left: 52.5%;
          animation-delay: 0.6s;
        }
        &:nth-child(4) {
          top: 59%;
          left: 35.5%;
          animation-delay: 0.8s;
        }
        &:nth-child(5) {
          top: 65%;
          left: 65.5%;
          animation-delay: 1s;
        }
        &:nth-child(6) {
          top: 82%;
          left: 50.5%;
          animation-delay: 1.2s;
        }
      }

      .detail-layer {
        position: absolute;
        left: 50%;
        top: 50%;
        transform: translate(-50%, -50%);
        width: 53%;
        height: 72%;
        background: rgba(168, 95, 55, 0.88);
        border-radius: 49px;
        backdrop-filter: blur(2px);
        color: rgba(255, 255, 255, 0.9);
        display: flex;
        flex-direction: column;
        align-items: center;
        justify-content: center;

        .title {
          padding: 0 0.12rem;
          font-family: Rakkas;
          font-size: 0.42rem;
          line-height: 1.75;
          text-align: center;
        }

        .text {
          padding: 0 0.12rem;
          font-family: Rakkas;
          font-size: 0.36rem;
          line-height: 1.75;
        }
      }
    }
  }
}

#app {
  font-family: Avenir, Helvetica, Arial, sans-serif;
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
  overflow-x: hidden;
}
</style>
